services:
  ros-core:
    image: osrf/ros:noetic-desktop-full
    container_name: ros-core
    command: "rosmaster --core"
    network_mode: host
    stop_grace_period: 1s
    healthcheck:
      # The healthcheck is required for ros1-bridge to wait until roscore is ready.
      test: /ros_entrypoint.sh bash -c "rostopic list || exit 1"
      interval: 3s
      timeout: 10s
      retries: 5

  ros1-bridge:
    build:
      context: .
      target: release
    image: pomelo925/ttennis-humble:communication
    container_name: ros2-ros1-bridge-ws
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=23
    stop_grace_period: 1s
    depends_on:
      ros-core:
        # The healthcheck is required for ros1-bridge to wait until roscore is ready.
        condition: service_healthy
    command: ["/bin/bash", "./start-bridge.sh"]
    stdin_open: true
    tty: true
    network_mode: host
    working_dir: /
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Direct Rendering Infrastructure
      - /dev/dri:/dev/dri
      # Shared Memory
      - /dev/shm:/dev/shm
      - ~/TDK/E.Commnication/comm-ws:/home/user/E.Communication/comm-ws/

  ros1:
    image: osrf/ros:noetic-desktop-full
    container_name: ros1
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - ~/TDK/E.Commnication/comm-ws:/home/user/E.Communication/comm-ws/
      - /dev/bus/usb:/dev/bus/usb
    stop_grace_period: 1s
    depends_on:
      ros-core:
        condition: service_healthy
    command: /bin/bash -c "
            source /opt/ros/noetic/setup.bash && 
            source /root/comm-ws/devel/setup.bash && 
            cd /root/comm-ws &&
            sudo chmod 777 /dev/ttyUSB0 &&
            roslaunch rosserial_server stm32.launch"
        

  ros2:
    image: osrf/ros:humble-desktop-full
    container_name: ros2
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=23
    stdin_open: true
    tty: true
    network_mode: host
    stop_grace_period: 1s
    volumes:
      # Shared Memory
      - /dev/shm:/dev/shm
      - ~/TDK/E.Commnication/comm-ws:/home/user/E.Communication/comm-ws/
    command: /bin/bash -c "apt update && apt install -y ros-humble-rmw-cyclonedds-cpp && source /opt/ros/humble/setup.bash && bash"